version: '2'
catalog:
  name: "GitBucket"
  version: "v4.26.0"
  description: ""
  questions:
      - variable: "public_port"
        label: "Public Port"
        description: "Public listening port"
        type: "int"
        required: true
        default: "8200"
      - variable: "ssh_port"
        label: "SSH Port"
        description: "SSH listening port"
        type: "int"
        required: true
        default: "29418"
      - variable: "db_url"
        label: "DB URL"
        description: "DB URL"
        type: "string"
      - variable: "db_user"
        label: "DB USER"
        description: "DB USER"
        type: "string"
      - variable: "db_password"
        label: "DB PASSWORD"
        description: "DB PASSWORD"
        type: "password"
services:
  gitbucket-primary:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  gitbucket-datavolume:
    scale: 1
    start_on_create: true
